### ISSUE TITLE
Tool breaks System restore

### ISSUE THREAD

**Issue by Hari-Pi** [eliasailenei/SkipOOBE#1]
Yes the tool works amazingly well and skips OOBE but in turn i've noticed it breaks System Restore and I have attached a screenshot of the error below
![28 2022-09-11](https://user-images.githubusercontent.com/71986052/189514207-12327307-4637-4995-93a4-701191e03cff.jpg)

**Comment by eliasailenei** [comment]
Thanks for letting me know, there is a solution that might fix that. 

Head to Registry Editor and head to:
Computer\HKEY_LOCAL_MACHINE\SYSTEM\Setup

Then remove the code from RespecializeCmdLine

This is due to being stuck in SysPrep mode. I knew about this issue but I was too lazy. I will update the tool now!

**Comment by Hari-Pi** [comment]
Great I'll test the tool again and let you know if the issue persists
